"""
Canonical log parser for OpenCode NDJSON output.

This is the single source of truth for parsing OpenCode log files in dlab.
All other modules (timeline.py, tui/log_watcher.py, tui/models.py) import
from here instead of doing their own JSON parsing.

OpenCode logs are NDJSON (one JSON object per line) with stderr mixed in
because dlab runs opencode with `2>&1 | tee`. Lines can be:
- JSON events (OpenCode step/text/tool events)
- Raw text (stderr from startup, database migrations, etc.)
- [STDERR] prefixed lines (from some logging paths)

Event types (from OpenCode source: packages/opencode/src/session/message-v2.ts):
- step_start: Agent step begins (part: snapshot?)
- step_finish: Agent step ends (part: reason, cost, tokens)
- text: Agent text output (part: text, time?, metadata?)
- tool_use: Tool invocation (part: tool, callID, state)
- error: Session error (error: {name, data: {message, statusCode}})
- reasoning: Extended thinking (part: text, time)

Synthetic types (generated by this parser for non-JSON content):
- raw_text: Non-JSON lines (stderr, startup messages)
- additional_output: JSON without type/timestamp (tool output fragments)

Tool state machine: pending → running → completed | error
Step finish reasons: stop, tool-calls, error, max-tokens, unknown
"""

import json
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any, Iterator


def ms_to_datetime(timestamp_ms: int) -> datetime:
    """
    Convert millisecond timestamp to datetime.

    Parameters
    ----------
    timestamp_ms : int
        Timestamp in milliseconds since epoch.

    Returns
    -------
    datetime
        Local datetime.
    """
    return datetime.fromtimestamp(timestamp_ms / 1000)


@dataclass
class LogEvent:
    """
    A single parsed log event.

    Attributes
    ----------
    event_type : str
        Event type: step_start, step_finish, text, tool_use, error,
        raw_text, additional_output, reasoning.
    timestamp : int | None
        Milliseconds since epoch. None for raw_text/additional_output.
    session_id : str
        OpenCode session ID (empty for synthetic events).
    part : dict[str, Any]
        Event-specific data (the "part" field from the JSON line).
    raw : dict[str, Any]
        Full raw JSON line (empty dict for raw_text).
    """

    event_type: str
    timestamp: int | None
    session_id: str
    part: dict[str, Any]
    raw: dict[str, Any]


def parse_line(line: str) -> LogEvent | None:
    """
    Parse a single log line into a LogEvent.

    Parameters
    ----------
    line : str
        Raw line from log file.

    Returns
    -------
    LogEvent | None
        Parsed event, or None for empty lines.
    """
    line = line.strip()
    if not line:
        return None

    # [STDERR] prefixed lines → raw_text
    if line.startswith("[STDERR]"):
        return LogEvent(
            event_type="raw_text",
            timestamp=None,
            session_id="",
            part={"text": line},
            raw={},
        )

    # Try JSON parsing
    if line.startswith("{"):
        try:
            data: dict[str, Any] = json.loads(line)
        except json.JSONDecodeError:
            # Looks like JSON but isn't → raw_text
            return LogEvent(
                event_type="raw_text",
                timestamp=None,
                session_id="",
                part={"text": line},
                raw={},
            )

        event_type: str | None = data.get("type")
        timestamp: int | None = data.get("timestamp")

        if event_type and timestamp is not None:
            # Normal OpenCode event
            return LogEvent(
                event_type=event_type,
                timestamp=timestamp,
                session_id=data.get("sessionID", ""),
                part=data.get("part", {}),
                raw=data,
            )
        else:
            # JSON but missing type/timestamp → additional_output
            return LogEvent(
                event_type="additional_output",
                timestamp=None,
                session_id="",
                part={"raw_data": data},
                raw=data,
            )

    # Plain text → raw_text
    return LogEvent(
        event_type="raw_text",
        timestamp=None,
        session_id="",
        part={"text": line},
        raw={},
    )


def parse_log_file(path: str | Path) -> list[LogEvent]:
    """
    Parse a log file into a list of events.

    Groups consecutive raw_text events into single events.

    Parameters
    ----------
    path : str | Path
        Path to the log file.

    Returns
    -------
    list[LogEvent]
        Parsed events in file order.
    """
    log_path: Path = Path(path)
    if not log_path.exists():
        return []

    events: list[LogEvent] = []
    raw_text_lines: list[str] = []

    def flush_raw_text() -> None:
        if raw_text_lines:
            events.append(LogEvent(
                event_type="raw_text",
                timestamp=None,
                session_id="",
                part={"text": "\n".join(raw_text_lines)},
                raw={},
            ))
            raw_text_lines.clear()

    with open(log_path, "r") as f:
        for line in f:
            event: LogEvent | None = parse_line(line)
            if event is None:
                continue

            if event.event_type == "raw_text":
                raw_text_lines.append(event.part.get("text", ""))
            else:
                flush_raw_text()
                events.append(event)

    flush_raw_text()
    return events


def iter_log_events(path: str | Path) -> Iterator[LogEvent]:
    """
    Iterate over log events from a file (generator, no grouping).

    Parameters
    ----------
    path : str | Path
        Path to the log file.

    Yields
    ------
    LogEvent
        Each parsed event.
    """
    log_path: Path = Path(path)
    if not log_path.exists():
        return

    with open(log_path, "r") as f:
        for line in f:
            event: LogEvent | None = parse_line(line)
            if event is not None:
                yield event


def is_log_complete(events: list[LogEvent]) -> bool:
    """
    Check if a list of events represents a completed run.

    A log is complete if:
    - Its last step_finish event has reason "stop" or "error", OR
    - It contains an "error" event (job crashed/terminated)

    Parameters
    ----------
    events : list[LogEvent]
        Parsed events from a log file.

    Returns
    -------
    bool
        True if the log shows a completed run.
    """
    if not events:
        return False

    last_step_finish: LogEvent | None = None
    has_error: bool = False

    for event in events:
        if event.event_type == "step_finish":
            last_step_finish = event
        elif event.event_type == "error":
            has_error = True

    if has_error:
        return True

    if last_step_finish is None:
        return False

    reason: str = last_step_finish.part.get("reason", "")
    return reason in ("stop", "error")


def is_log_file_complete(path: str | Path) -> bool:
    """
    Check if a log file represents a completed run.

    Convenience wrapper that parses the file and checks completion.

    Parameters
    ----------
    path : str | Path
        Path to the log file.

    Returns
    -------
    bool
        True if the log shows a completed run.
    """
    return is_log_complete(parse_log_file(path))


# ---------------------------------------------------------------------------
# Event accessor helpers
# ---------------------------------------------------------------------------


def get_tool_name(event: LogEvent) -> str | None:
    """Get the tool name from a tool_use event, or None."""
    if event.event_type != "tool_use":
        return None
    return event.part.get("tool")


def get_tool_status(event: LogEvent) -> str | None:
    """Get the tool status (pending/running/completed/error), or None."""
    if event.event_type != "tool_use":
        return None
    return event.part.get("state", {}).get("status")


def get_tool_input(event: LogEvent) -> dict[str, Any] | None:
    """Get the tool input dict, or None."""
    if event.event_type != "tool_use":
        return None
    return event.part.get("state", {}).get("input")


def get_tool_output(event: LogEvent) -> str | None:
    """Get the tool output string, or None."""
    if event.event_type != "tool_use":
        return None
    return event.part.get("state", {}).get("output")


def get_tool_error(event: LogEvent) -> str | None:
    """Get the tool error string, or None."""
    if event.event_type != "tool_use":
        return None
    return event.part.get("state", {}).get("error")


def get_tool_time(event: LogEvent) -> tuple[int | None, int | None]:
    """Get (start_ms, end_ms) from a tool_use event."""
    if event.event_type != "tool_use":
        return None, None
    time_data: dict[str, Any] = event.part.get("state", {}).get("time", {})
    return time_data.get("start"), time_data.get("end")


def get_step_reason(event: LogEvent) -> str | None:
    """Get the step finish reason, or None."""
    if event.event_type != "step_finish":
        return None
    return event.part.get("reason")


def get_step_cost(event: LogEvent) -> float | None:
    """Get the step cost, or None."""
    if event.event_type != "step_finish":
        return None
    cost: float = event.part.get("cost", 0.0)
    return cost if cost else None


def get_step_tokens(event: LogEvent) -> dict[str, Any] | None:
    """
    Get the token usage dict from a step_finish event.

    Returns dict with: total, input, output, reasoning, cache.read, cache.write
    """
    if event.event_type != "step_finish":
        return None
    tokens: dict[str, Any] = event.part.get("tokens", {})
    return tokens if tokens else None


def get_text(event: LogEvent) -> str | None:
    """Get the text content from a text or raw_text event, or None."""
    if event.event_type in ("text", "raw_text"):
        return event.part.get("text")
    return None


def get_dlab_start_model(events: list[LogEvent]) -> str | None:
    """
    Extract model from the first dlab_start event, or None for older logs.

    Parameters
    ----------
    events : list[LogEvent]
        Parsed events from a log file.

    Returns
    -------
    str | None
        Model string (e.g. "anthropic/claude-sonnet-4-5") or None.
    """
    for event in events:
        if event.event_type == "dlab_start":
            return event.part.get("model") or event.raw.get("model")
        # Only check the first few events — dlab_start is always first
        if event.timestamp is not None:
            break
    return None


# ---------------------------------------------------------------------------
# Session graph
# ---------------------------------------------------------------------------


@dataclass
class SessionNode:
    """
    A node in the session execution graph.

    Attributes
    ----------
    name : str
        Node name (e.g. "main", "instance-1", "consolidator").
    log_path : Path
        Path to the .log file.
    events : list[LogEvent]
        Parsed events from this log.
    children : list[SessionNode]
        Child nodes (parallel instances + consolidator).
    parent_event_index : int | None
        Index in parent's events where this node was spawned.
    agent_name : str
        Agent name (e.g. "data-preparer", "modeler", "main").
    is_consolidator : bool
        Whether this is a consolidator node.
    model : str | None
        Model used (from dlab_start event, or None for older logs).
    """

    name: str
    log_path: Path
    events: list[LogEvent] = field(default_factory=list)
    children: list["SessionNode"] = field(default_factory=list)
    parent_event_index: int | None = None
    agent_name: str = ""
    is_consolidator: bool = False
    model: str | None = None

    def __repr__(self) -> str:
        return self._repr_tree()

    def _repr_tree(self) -> str:
        """Render the session graph as a timeline showing main events between subagent calls."""
        if not self.children:
            # Leaf node or no parallel agents
            n: int = len(self.events)
            model_str: str = f" ({self.model})" if self.model else ""
            complete: str = "✓" if is_log_complete(self.events) else "…"
            return f"{self.name} [{n} events{model_str}] {complete}"

        lines: list[str] = []
        model_str = f" ({self.model})" if self.model else ""
        complete = "✓" if is_log_complete(self.events) else "…"
        lines.append(f"{self.name}{model_str} {complete}")

        # Group children by parent_event_index to show them at the right point
        spawn_points: dict[int | None, list["SessionNode"]] = {}
        for child in self.children:
            idx: int | None = child.parent_event_index
            if idx not in spawn_points:
                spawn_points[idx] = []
            spawn_points[idx].append(child)

        # Walk through main events, inserting children at spawn points
        prev_idx: int = 0
        sorted_indices: list[int] = sorted(i for i in spawn_points if i is not None)

        for spawn_idx in sorted_indices:
            # Count main events before this spawn
            events_before: int = spawn_idx - prev_idx
            if events_before > 0:
                lines.append(f"│ ... {events_before} events ...")

            # Show spawned children
            children: list["SessionNode"] = spawn_points[spawn_idx]
            for i, child in enumerate(children):
                is_last_child: bool = i == len(children) - 1
                connector: str = "└── " if is_last_child else "├── "
                agent_prefix: str = f"{child.agent_name}/" if child.agent_name != child.name else ""
                n_events: int = len(child.events)
                child_model: str = f" ({child.model})" if child.model else ""
                child_complete: str = "✓" if is_log_complete(child.events) else "…"
                lines.append(f"{connector}{agent_prefix}{child.name} [{n_events} events{child_model}] {child_complete}")

            prev_idx = spawn_idx + 1

        # Events after last spawn
        remaining: int = len(self.events) - prev_idx
        if remaining > 0:
            lines.append(f"│ ... {remaining} events ...")

        return "\n".join(lines)


def build_session_graph(logs_dir: str | Path) -> SessionNode | None:
    """
    Build a session execution graph from an _opencode_logs directory.

    The root node is main.log. Children are parallel agent instances
    and consolidators, linked by matching parallel-agents tool calls
    to their subfolder logs.

    Parameters
    ----------
    logs_dir : str | Path
        Path to the _opencode_logs directory.

    Returns
    -------
    SessionNode | None
        Root node of the session graph, or None if main.log doesn't exist.
    """
    logs_path: Path = Path(logs_dir)
    main_log: Path = logs_path / "main.log"

    if not main_log.exists():
        return None

    main_events: list[LogEvent] = parse_log_file(main_log)
    root: SessionNode = SessionNode(
        name="main",
        log_path=main_log,
        events=main_events,
        agent_name="main",
        model=get_dlab_start_model(main_events),
    )

    # Find all parallel-agents tool calls in main log
    for event_idx, event in enumerate(main_events):
        if event.event_type != "tool_use":
            continue
        if event.part.get("tool") != "parallel-agents":
            continue
        state: dict[str, Any] = event.part.get("state", {})
        if state.get("status") != "completed":
            continue

        input_data: dict[str, Any] = state.get("input", {})
        agent_name: str = input_data.get("agent", "")
        if not agent_name:
            continue

        # Find matching subfolder
        run_dir: Path | None = _find_parallel_run_dir(
            logs_path, agent_name, state.get("time", {}),
        )
        if run_dir is None:
            continue

        # Parse instance logs
        instance_logs: list[Path] = sorted(run_dir.glob("instance-*.log"))
        for instance_log in instance_logs:
            instance_events: list[LogEvent] = parse_log_file(instance_log)
            child: SessionNode = SessionNode(
                name=instance_log.stem,
                log_path=instance_log,
                events=instance_events,
                parent_event_index=event_idx,
                agent_name=agent_name,
                model=get_dlab_start_model(instance_events),
            )
            root.children.append(child)

        # Parse consolidator log if present
        consolidator_log: Path = run_dir / "consolidator.log"
        if consolidator_log.exists():
            cons_events: list[LogEvent] = parse_log_file(consolidator_log)
            cons_node: SessionNode = SessionNode(
                name="consolidator",
                log_path=consolidator_log,
                events=cons_events,
                parent_event_index=event_idx,
                agent_name=agent_name,
                is_consolidator=True,
                model=get_dlab_start_model(cons_events),
            )
            root.children.append(cons_node)

    return root


def _find_parallel_run_dir(
    logs_dir: Path,
    agent_name: str,
    time_data: dict[str, Any],
) -> Path | None:
    """
    Find the parallel run subfolder matching an agent name.

    Matches by agent name prefix. If multiple matches, picks the one
    with closest timestamp.

    Parameters
    ----------
    logs_dir : Path
        The _opencode_logs directory.
    agent_name : str
        Agent name from the parallel-agents tool call.
    time_data : dict[str, Any]
        Time data from the tool call state (has "start" key).

    Returns
    -------
    Path | None
        Path to the matching run directory, or None.
    """
    prefix: str = f"{agent_name}-parallel-run-"
    candidates: list[Path] = [
        d for d in logs_dir.iterdir()
        if d.is_dir() and d.name.startswith(prefix)
    ]

    if not candidates:
        return None

    if len(candidates) == 1:
        return candidates[0]

    # Multiple matches — pick closest timestamp
    tool_start: int = time_data.get("start", 0)
    if not tool_start:
        return candidates[0]

    def ts_distance(d: Path) -> int:
        try:
            folder_ts: int = int(d.name[len(prefix):])
            return abs(folder_ts - tool_start)
        except ValueError:
            return 10**18

    return min(candidates, key=ts_distance)
