"""
Integration tests for generate_dpack with Docker builds.

Tests that decision-packs generated by generate_dpack() for each package manager
with modal_integration=True produce working Docker images where:
1. The modal pre-run hook runs without conda activation issues
2. `python` resolves to the correct managed python
3. `modal` is importable

Run all:
    pytest tests/test_generate_dpack_integration.py -v -s

Run one package manager:
    pytest tests/test_generate_dpack_integration.py::TestConda -v -s
    pytest tests/test_generate_dpack_integration.py::TestPip -v -s
    pytest tests/test_generate_dpack_integration.py::TestUv -v -s
    pytest tests/test_generate_dpack_integration.py::TestPixi -v -s
"""

import subprocess
import tempfile
import uuid
from pathlib import Path
from typing import Any, Generator

import pytest

from dlab.create_dpack import generate_dpack
from dlab.docker import (
    build_image,
    exec_command,
    start_container,
    stop_container,
)


def _remove_image(name: str) -> None:
    """Remove a Docker image, ignoring errors if it doesn't exist."""
    subprocess.run(["docker", "rmi", "-f", name], capture_output=True)


EXPECTED_PYTHON_PATHS: dict[str, str] = {
    "conda": "/opt/conda/bin/python",
    "pip": "/usr/local/bin/python",
    "uv": "/usr/local/bin/python",
    "pixi": "/opt/pixi/.pixi/envs/default/bin/python",
}


def _run_in_container(image_name: str, command: list[str]) -> tuple[int, str, str]:
    """Start a container, run a command, stop it, return (exit_code, stdout, stderr)."""
    container_name: str = f"test-{uuid.uuid4().hex[:8]}"
    work_dir: Path = Path(f"/tmp/test-work-{container_name}")
    work_dir.mkdir(parents=True, exist_ok=True)
    (work_dir / "_opencode_logs").mkdir(exist_ok=True)

    try:
        start_container(image_name, str(work_dir), container_name)
        return exec_command(container_name, command)
    finally:
        stop_container(container_name)
        subprocess.run(["rm", "-rf", str(work_dir)], capture_output=True)


def _build_dpack_image(pkg_mgr: str) -> tuple[str, str, Path]:
    """Generate a dpack and build its Docker image. Returns (pkg_mgr, image_name, dpack_path)."""
    tmp_dir: Path = Path(tempfile.mkdtemp(prefix=f"dlab-inttest-{pkg_mgr}-"))
    name: str = f"inttest-{pkg_mgr}-{uuid.uuid4().hex[:6]}"
    image_name: str = f"dlab-{name}"

    config: dict[str, Any] = {
        "name": name,
        "package_manager": pkg_mgr,
        "modal_integration": True,
        "requires_data": False,
        "requires_prompt": False,
        "skeletons": {"tools": True},
    }

    dpack_path: Path = generate_dpack(tmp_dir, config)
    build_image(str(dpack_path), image_name, "latest")
    return pkg_mgr, image_name, dpack_path


def _cleanup_image(image_name: str) -> None:
    """Remove both wrapper and base images."""
    _remove_image(image_name)
    _remove_image(f"{image_name}-base")


# ---------------------------------------------------------------------------
# Per-package-manager fixtures (scope=class, built once per class)
# ---------------------------------------------------------------------------

@pytest.fixture(scope="class")
def conda_dpack() -> Generator[tuple[str, str, Path], None, None]:
    pkg_mgr, image_name, dpack_path = _build_dpack_image("conda")
    yield pkg_mgr, image_name, dpack_path
    _cleanup_image(image_name)


@pytest.fixture(scope="class")
def pip_dpack() -> Generator[tuple[str, str, Path], None, None]:
    pkg_mgr, image_name, dpack_path = _build_dpack_image("pip")
    yield pkg_mgr, image_name, dpack_path
    _cleanup_image(image_name)


@pytest.fixture(scope="class")
def uv_dpack() -> Generator[tuple[str, str, Path], None, None]:
    pkg_mgr, image_name, dpack_path = _build_dpack_image("uv")
    yield pkg_mgr, image_name, dpack_path
    _cleanup_image(image_name)


@pytest.fixture(scope="class")
def pixi_dpack() -> Generator[tuple[str, str, Path], None, None]:
    pkg_mgr, image_name, dpack_path = _build_dpack_image("pixi")
    yield pkg_mgr, image_name, dpack_path
    _cleanup_image(image_name)


# ---------------------------------------------------------------------------
# Shared test logic
# ---------------------------------------------------------------------------

def _test_python_resolves(dpack_info: tuple[str, str, Path]) -> None:
    pkg_mgr, image_name, _ = dpack_info
    exit_code, stdout, stderr = _run_in_container(image_name, ["which", "python"])
    python_path: str = stdout.strip()

    assert exit_code == 0, f"which python failed: {stderr}"
    assert python_path != "", "python not found on PATH"
    if pkg_mgr in EXPECTED_PYTHON_PATHS:
        assert python_path == EXPECTED_PYTHON_PATHS[pkg_mgr], (
            f"{pkg_mgr}: expected {EXPECTED_PYTHON_PATHS[pkg_mgr]}, got {python_path}"
        )


def _test_modal_importable(dpack_info: tuple[str, str, Path]) -> None:
    _, image_name, _ = dpack_info
    exit_code, stdout, stderr = _run_in_container(
        image_name, ["python", "-c", "import modal; print(modal.__version__)"]
    )
    assert exit_code == 0, f"import modal failed: {stderr}"
    assert stdout.strip() != "", "modal version empty"


def _test_deploy_hook(dpack_info: tuple[str, str, Path]) -> None:
    _, image_name, dpack_path = dpack_info
    container_name: str = f"test-hook-{uuid.uuid4().hex[:8]}"
    work_dir: Path = Path(f"/tmp/test-work-{container_name}")
    work_dir.mkdir(parents=True, exist_ok=True)
    (work_dir / "_opencode_logs").mkdir(exist_ok=True)

    hooks_dir: Path = work_dir / "_hooks"
    hooks_dir.mkdir()
    hook_dst: Path = hooks_dir / "deploy_modal.sh"
    hook_dst.write_text((dpack_path / "deploy_modal.sh").read_text())
    hook_dst.chmod(0o755)

    try:
        start_container(image_name, str(work_dir), container_name)

        exit_code, stdout, stderr = exec_command(
            container_name,
            ["bash", "-c", "DLAB_RUN_MODAL_TOOL_LOCALLY=1 /workspace/_hooks/deploy_modal.sh"],
        )
        assert exit_code == 0, f"Hook failed: {stderr}\n{stdout}"
        assert "Skipping Modal deployment" in stdout

        exit_code, stdout, stderr = exec_command(container_name, ["modal", "--help"])
        assert exit_code == 0, f"modal CLI not found: {stderr}"
    finally:
        stop_container(container_name)
        subprocess.run(["rm", "-rf", str(work_dir)], capture_output=True)


# ---------------------------------------------------------------------------
# Test classes (one per package manager)
# ---------------------------------------------------------------------------

class TestConda:
    """Integration tests for conda package manager."""

    def test_python_resolves_correctly(self, conda_dpack: tuple[str, str, Path]) -> None:
        _test_python_resolves(conda_dpack)

    def test_modal_importable(self, conda_dpack: tuple[str, str, Path]) -> None:
        _test_modal_importable(conda_dpack)

    def test_deploy_hook_runs_without_activation(self, conda_dpack: tuple[str, str, Path]) -> None:
        _test_deploy_hook(conda_dpack)


class TestPip:
    """Integration tests for pip package manager."""

    def test_python_resolves_correctly(self, pip_dpack: tuple[str, str, Path]) -> None:
        _test_python_resolves(pip_dpack)

    def test_modal_importable(self, pip_dpack: tuple[str, str, Path]) -> None:
        _test_modal_importable(pip_dpack)

    def test_deploy_hook_runs_without_activation(self, pip_dpack: tuple[str, str, Path]) -> None:
        _test_deploy_hook(pip_dpack)


class TestUv:
    """Integration tests for uv package manager."""

    def test_python_resolves_correctly(self, uv_dpack: tuple[str, str, Path]) -> None:
        _test_python_resolves(uv_dpack)

    def test_modal_importable(self, uv_dpack: tuple[str, str, Path]) -> None:
        _test_modal_importable(uv_dpack)

    def test_deploy_hook_runs_without_activation(self, uv_dpack: tuple[str, str, Path]) -> None:
        _test_deploy_hook(uv_dpack)


class TestPixi:
    """Integration tests for pixi package manager."""

    def test_python_resolves_correctly(self, pixi_dpack: tuple[str, str, Path]) -> None:
        _test_python_resolves(pixi_dpack)

    def test_modal_importable(self, pixi_dpack: tuple[str, str, Path]) -> None:
        _test_modal_importable(pixi_dpack)

    def test_deploy_hook_runs_without_activation(self, pixi_dpack: tuple[str, str, Path]) -> None:
        _test_deploy_hook(pixi_dpack)
